#!/bin/bash

CYAN="\e[0;36m"
RED="\e[0;91m"
NORMAL="\e[0m"
BOLD="\e[1m"

function info() {
	echo -e "${CYAN}${1}${NORMAL}"
}

function warning() {
	echo -e "${RED}${1}${NORMAL}"
}

function abort() {
	printf "  ${RED}%s[%s]:${NORMAL}" "${BASH_SOURCE[1]}" ${BASH_LINENO[0]}
	echo -e " ${RED}${REVERSE}$@${NORMAL} ${RED}Aborting...${NORMAL}"
	exit 2
}

which_path() {
	./chroot-gentoo -c "which $1" 2>/dev/null
}

matching_packages() {
	OUT=$(./chroot-gentoo -c "eix --only-names --exact $1")

	if [ -z "${OUT}" ]; then
		OUT=$(./chroot-gentoo -c "eix --only-names $1")
	fi

	echo "$OUT"
}

while (( "$#" )); do
	case "$1" in
		"--name")
			NAME=$2
			shift 2
			;;
		"--dest")
			DEST=$2
			shift 2
			;;
		"--pkg-hint")
			PKG_HINT=$2
			shift 2
			;;
		*)
			# Options to pass to mk-labs-bootstrap from here on.
			# This is not ideal since these options *must* be given
			# after the ones above for this own script, but that
			# should be the case in any normal situation
			break
			;;
	esac
done

if [ -z "$NAME" ]; then
	echo "Usage: $0 <executable file>"
	exit
fi

# Try to find the executable in the stage3

EXE=$(which_path "${NAME}")

if [ -z "${EXE}" ]; then

	echo "-------------------------------------------------"
	warning "'${NAME}' executable not found in the chroot system."

	if [ -n "${PKG_HINT}" ]; then
		package="${PKG_HINT}"
	else
		package=$(matching_packages "${NAME}")
	fi


	if [ -z "$package" ]; then
		abort "No package matching '${BOLD}$package${NORMAL}' was found, sorry."
	elif [[ "$package" =~ $'\n' ]]; then
		info "More than one package matching that name was found, maybe you want one of them?"
		echo "$package" | sed 's/^/  - /'
		info "If you want to install one of them, run ./chroot-gentoo -c 'emerge -v <package name>'"
		exit 1
	else
		info "Found matching package ${BOLD}${package}${NORMAL}."
		count=5
		if test -n "$CI"; then
			# CI build... no point in waiting
			count=0
		fi
		warning "Installing it in ${count} seconds, press Ctrl+C to abort!"
		while ((count-- > 0)); do
			echo -n "$((count+1))... "
			sleep 1
		done
		echo -e "\nRunning ./chroot-gentoo -c 'emerge ${package}'"
		./chroot-gentoo -c "emerge ${package}" \
			|| abort "failed to emerge ${package}"
	fi



	echo "-------------------------------------------------"

	EXE=$(which_path "${NAME}")

	if [ -z "${EXE}" ]; then
		abort "Still not finding ${NAME}, don't know what more to do, sorry..."
	fi
fi

if [ -z "$DEST" ]; then
	DEST="${NAME}.tar.gz"
fi

(
	[ "$QUIET" ] && exec &>/dev/null

	./mk-labs-bootstrap \
		--package \
		--chroot gentoo-stage3 \
		--add-exe "$EXE" \
		--dest "$DEST" \
		"$@"
)
ret=$?
if [ $ret = 0 ]; then
	echo -e "$DEST created, enjoy!"
else
	echo -e "Something wrong probably happened with ${EXE}, sorry..."
fi
exit $ret
