#!/bin/sh

FILE=labs-bootstrap-initramfs
REPO=ansible_repo

password=$(
awk -f- ${REPO}/roles/users/vars/main.yml <<EOF
	BEGIN {
		FS="'"; # Field Separator
	}
	/name: 'root'/{
		user=1;
	}
	user && /password/ {
		print \$2;
		exit;
	}
EOF
)

ansible all -i localhost, -c local -m template -a "src=${REPO}/roles/ssh/templates/sshd_config.j2 dest=/dev/shm/sshd_config" --extra-vars=@/root/ansible-rework/roles/ssh/vars/main.yml

./mk-labs-bootstrap \
	--initramfs \
	--chroot gentoo-stage3 \
	--ssh-config /dev/shm/sshd_config \
	--ssh-host-keys-dir ${REPO}/roles/ssh/files/etc/ssh \
	--ssh-authorized-keys ${REPO}/roles/ssh/files/root/.ssh/authorized_keys \
	--root-password "$password" \
	--add-ca "/usr/local/share/ca-certificates/RNLcacert.crt" \
	--dest "$FILE" \
	"$@"

if [ $? = 0 ]; then
	echo -e "\n$FILE created, enjoy!"
else
	echo e "\nSomething wrong probably happened, sorry..."
fi
