#!/bin/sh

FILE=labs-bootstrap-initramfs

password=$(
awk -f- /root/rnlinux/roles/users/vars/main.yml <<EOF
	BEGIN {
		FS="'"; # Field Separator
	}
	/name: 'rnladmin'/{
		user=1;
	}
	user && /password/ {
		print \$2;
		exit;
	}
EOF
)

./mk-labs-bootstrap \
	--initramfs \
	--chroot /root/labs-bootstrap/gentoo-chroot \
	--ssh-config ~/rnlinux/roles/ssh/files/etc/ssh/sshd_config \
	--ssh-host-keys-dir ~/rnlinux/roles/ssh/files/etc/ssh \
	--ssh-authorized-keys ~/rnlinux/roles/ssh/files/root/.ssh/authorized_keys \
	--root-password "$password" \
	--ca "/usr/local/share/ca-certificates/RNLcacert.crt" \
	--dest "$FILE" \
	"$@"

if [ $? = 0 ]; then
	echo -e "\n$FILE created, enjoy!"
else
	echo e "\nSomething wrong probably happened, sorry..."
fi
