#!/bin/bash

NAME="$1"
DEST="$2"

which_path() {
	./chroot-gentoo -c "which $1" 2>/dev/null
}

matching_packages() {
	OUT=$(./chroot-gentoo -c "eix --only-names --exact $1")

	if [ -z "${OUT}" ]; then
		OUT=$(./chroot-gentoo -c "eix --only-names $1")
	fi

	echo "$OUT"
}

if [ -z "$NAME" ]; then
	echo "Usage: $0 <executable file>"
	exit
else
	shift
fi

EXE=$(which_path "${NAME}")

if [ -z "${EXE}" ]; then

	echo "-------------------------------------------------"
	echo "'${NAME}' not found in the chroot system."

	package=$(matching_packages "${NAME}")

	if [ -z "$package" ]; then
		echo "No package matching that name found, sorry."

	elif [[ "$package" =~ $'\n' ]]; then
		echo "More than one package matching that name was found, maybe you want one of them?"
		echo "$package" | sed 's/^/  - /'
		echo "If you want to install one of them, run ./chroot-gentoo -c 'emerge -v <package name>'"
	else
		echo "Found matching package ${package}."
		echo "If you want to install it, run ./chroot-gentoo -c 'emerge -v ${package}'"
	fi

	echo "-------------------------------------------------"
	exit 1
fi

FILE="$(basename $EXE).tar.gz"

if [ -z "$DEST" ]; then
	DEST=$FILE
else
	shift
fi

(
	[ "$QUIET" ] && exec &>/dev/null

	./mk-labs-bootstrap \
		--package \
		--chroot /root/labs-bootstrap/gentoo-chroot \
		--add-exe "$EXE" \
		--dest "$DEST" \
		"$@"
)

if [ $? = 0 ]; then
	echo -e "$DEST created, enjoy!"
else
	echo e "Something wrong probably happened with ${EXE}, sorry..."
fi
