#!/bin/sh

PKG_DIR=/var/www/geminio/packages

./create-package "/usr/bin/strace"  "${PKG_DIR}/strace.tar.gz"
./create-package "/usr/sbin/parted" "${PKG_DIR}/parted.tar.gz"
./create-package "/sbin/mkfs.ext4"  "${PKG_DIR}/mkfs.ext4.tar.gz"


### Custom transmission package

./transmission_config_filter.awk > /tmp/transmission_settings.json

./mk-labs-bootstrap \
	--package \
	--chroot /root/labs-bootstrap/gentoo-chroot \
	--add-exe /usr/bin/transmission-daemon \
	--copy-dir /usr/share/transmission/web /usr/share/transmission/web \
	--add-external-file /tmp/transmission_settings.json /var/lib/transmission/settings.json \
	--create-dir /torrents \
	--create-dir /downloads \
	--create-dir /incomplete \
	--dest "${PKG_DIR}"/transmission.tar.gz
