#!/bin/bash

BOOTSTRAP_OPTIONS=""

while (( "$#" )); do
	case "$1" in
		"--name")
			NAME=$2
			shift 2
			;;
		"--dest")
			DEST=$2
			shift 2
			;;
		"--pkg-hint")
			PKG_HINT=$2
			shift 2
			;;
		*)
			# Options to pass to mk-labs-bootstrap from here on.
			# This is not ideal since these options *must* be given
			# after the ones above for this own script, but that
			# should be the case in any normal situation
			break
			;;
	esac
done

CYAN="\e[0;36m"
RED="\e[0;31m"
NORMAL="\e[0m"

function info() {
	echo -e "${CYAN}${1}${NORMAL}"
}

function warning() {
	echo -e "${RED}${1}${NORMAL}"
}

which_path() {
	./chroot-gentoo -c "which $1" 2>/dev/null
}

matching_packages() {
	OUT=$(./chroot-gentoo -c "eix --only-names --exact $1")

	if [ -z "${OUT}" ]; then
		OUT=$(./chroot-gentoo -c "eix --only-names $1")
	fi

	echo "$OUT"
}

if [ -z "$NAME" ]; then
	echo "Usage: $0 <executable file>"
	exit
fi

EXE=$(which_path "${NAME}")

if [ -z "${EXE}" ]; then

	echo "-------------------------------------------------"
	warning "'${NAME}' executable not found in the chroot system."

	if [ -n "${PKG_HINT}" ]; then
		package="${PKG_HINT}"
	else
		package=$(matching_packages "${NAME}")
	fi


	if [ -z "$package" ]; then
		warning "No package matching that name found, sorry."
		exit 1

	elif [[ "$package" =~ $'\n' ]]; then
		warning "More than one package matching that name was found, maybe you want one of them?"
		echo "$package" | sed 's/^/  - /'
		info "If you want to install one of them, run ./chroot-gentoo -c 'emerge -v <package name>'"
		exit 1
	else
		info "Found matching package ${package}."
		count=5
		warning "Installing it in ${count} seconds, press Ctrl+C to abort!"
		while ((count-- > 0)); do
			echo -n "$((count+1))... "
			sleep 1
		done
		echo -e "\nRunning ./chroot-gentoo -c 'emerge ${package}'"
		./chroot-gentoo -c "emerge ${package}"
	fi



	echo "-------------------------------------------------"

	EXE=$(which_path "${NAME}")

	if [ -z "${EXE}" ]; then
		warning "Still not finding ${NAME}, don't know what more to do, sorry..."
		exit
	fi
fi

FILE="$(basename $EXE).tar.gz"

if [ -z "$DEST" ]; then
	DEST=$FILE
fi

(
	[ "$QUIET" ] && exec &>/dev/null

	./mk-labs-bootstrap \
		--package \
		--chroot /root/labs-bootstrap/gentoo-stage3 \
		--add-exe "$EXE" \
		--dest "$DEST" \
		"$@"
)

if [ $? = 0 ]; then
	echo -e "$DEST created, enjoy!"
else
	echo e "Something wrong probably happened with ${EXE}, sorry..."
fi
